name: 'build'

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: setup node 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: install npm
      run: npm clean-install

    - name: test
      run: |
        npm run test

    - name: build
      if: runner.os == 'Linux'
      run: |
        npm run build
